name: Reusable Workflow
on: 
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: echo "This is a reusable workflow!"

#create main.yml in same repo or another repo

name: Main Workflow
on:
    push
        
jobs:
    build:
        uses: ./.github/workflows/reusable.yml
